[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fl-evite-plus"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.16.0",
    "flwr-datasets[vision]>=0.5.0",
    "scikit-learn>=1.6.1",
    "networkx>=3.4.2",
    "pandas>=2.2.3",
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "atinzad"

[tool.flwr.app.components]
serverapp = "fl_evite_plus.server_app:app"
clientapp = "fl_evite_plus.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 10
penalty = "l2"
local-epochs = 1
communication_energy_per_bit = 0.0001  # Energy per bit (adjustable)
communication_distance_min = 0.0         # Minimum communication distance (adjustable)
communication_distance_max = 100        # Maximum communication distance (adjustable)
mst_file = "generated_trees/tree_config_05_10_1_2.json"
fraction_fit = 1.0                     # Fraction of clients to participate in training
fraction_evaluate = 1.0                # Fraction of clients to participate in evaluation
communication_error_rate = 0.0         # Probability of simulated communication failure (10%)
distance_file = "client_distances.csv"   # Path (relative or absolute)


[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 101
